name: Release CSI-Powermax
# Invocable as a reusable workflow
# Can be manually triggered
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select version to release'
        required: true
        type: choice
        default: 'minor'
        options:
          - major
          - minor
          - patch
      reverseproxyCheckInput:
          description: 'Release CSI-ReverseProxy Image'
          type: boolean
          default: false
          required: false
jobs:
  # process-input:
  #   name: Process images inputs
  #   runs-on: ubuntu-latest
  #   outputs:
  #     images: ${{ steps.process-input.outputs.imagelist }}
  #   steps:
  #     - name: Process images input
  #       id: process-images-input
  #       run: |
  #         # by default we will release only csi-powermax image, if the user selects reverse-proxy then we will release that as well.
  #         IMAGES="csi-powermax"
  #         if [ "${{ github.event.inputs.reverseproxyCheckInput }}" == "true" ]; then
  #           IMAGES="csi-powermax,csi-reverseproxy"
  #         fi
  #         echo "imagelist=$IMAGES" >> $GITHUB_OUTPUT
  csm-release:
    uses: harishp8889/test-common-github-actions/.github/workflows/csm-release-driver-module.yaml@main
    # needs: process-input
    name: Release CSM Drivers and Modules
    with:
      version: ${{ github.event.inputs.option }}
      images: ${{ github.event.inputs.reverseproxyCheckInput == 'true' && 'csi-powermax,csi-reverseproxy' || 'csi-powermax' }}

    secrets: inherit
